### ISSUE TITLE
命令行运行没有任何结果

### ISSUE THREAD

**Issue by DonCN** [smslit/comtrade#3]
使用命令行运行时，试了各种命令，没有结果出现啊。只有在vscode中调用comtrade.py运行才可以。

**Comment by okooo5km** [comment]
@DonCN 在 windows 下 ，保证 python3 安装路径已经在系统环境变量PATH中，即CMD下可以调用 python3 命令，此时可以使用 python3 运行 comtrade.py 脚本.
